# Generated by Django 4.2.7 on 2026-02-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-exam_date']},
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='end_date',
            new_name='exam_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_date',
        ),
    ]
